branches:
  except:
    - gh-pages
language: Ruby
complier:
  - gcc
before_install:
  - sudo apt-get install aspell-es
script: OUTPUT=`cat receta.md | aspell list -d es -p ./.aspell.es.pws`; if [ -n "$OUTPUT" ]; then echo $OUTPUT; exit 1; fi
